services:
  museumof_db:
    image: postgres:16.3
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: museumof
      POSTGRES_PASSWORD: test1234
    restart: always
    volumes:
      - museumof_db_data:/var/lib/postgresql/data
    networks:
      - museumof_net

  museumof_keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_ADMIN=museumof
      - KEYCLOAK_ADMIN_PASSWORD=test1234
    depends_on:
      - museumof_db
    restart: always
    command: start-dev --db=postgres --features=token-exchange --db-url=jdbc:postgresql://museumof_db:5432/museumof --db-username=museumof --db-password=test1234 --hostname=localhost
    networks:
      - museumof_net

networks:
  museumof_net:
    driver: bridge

volumes:
  museumof_db_data:
